### ISSUE TITLE
Manage conflicts

### ISSUE THREAD

**Issue by Soullivaneuh** [Soullivaneuh/php-cs-fixer-styleci-bridge#12]
https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/blob/dc7535933df0dab296e2df0d21c6be18a764b519/src/StyleCI/Fixers.php#L382

**Comment by GrahamCampbell** [comment]
Conflicts is something php-cs-fixer doesn't deal with, but styleci does to prevent bad config.

**Comment by Soullivaneuh** [comment]
> Conflicts is something php-cs-fixer doesn't deal with

Yeah I saw that. That's why I want to manage it myself too. :-)

**Comment by GrahamCampbell** [comment]
Right, I think I might have a better solution though. :)

**Comment by GrahamCampbell** [comment]
Can you add me on google hangouts?

**Comment by Soullivaneuh** [comment]
@GrahamCampbell What is your logic for conflict management?

Sample with psr0 and psr4. Which config file case would be errored?

**Comment by GrahamCampbell** [comment]
> What is your logic for conflict management?

We just check at the end when we're resolving the fixer list: https://github.com/StyleCI/Config/blob/master/src/Config.php#L540-L556.

> Sample with psr0 and psr4. Which config file case would be errored?

Using the psr0 fixer, an out of the box laravel app will be incorrectly fixed because it renames the namespace from App to app. My psr4 fixer won't do that.

**Comment by Soullivaneuh** [comment]
> Using the psr0 fixer, an out of the box laravel app will be incorrectly fixed because it renames the namespace from App to app. My psr4 fixer won't do that.

Yeah but I was talking about configuration.

For example, if I made this:

```yaml
preset: symfony

enabled:
  - psr0
  - psr4
```

Won't works (normal).

But if I try this? 

```yaml
preset: symfony

enabled:
  - psr4

disabled:
  - psr0
```

Will it work?

And if I try to add a fixer that is in conflict with one of the preset? What should it do?

**Comment by GrahamCampbell** [comment]
> Will it work?

Yes, that will work, at least until Sunday.

**Comment by GrahamCampbell** [comment]
The psr4 preset changes are not deployed to production yet.

**Comment by GrahamCampbell** [comment]
This is the version in production: https://github.com/StyleCI/Config/tree/4d5d04aa50b9a259aaa1aac55fe79e373f5ac9ea.

**Comment by Soullivaneuh** [comment]
I'm not talking about psr1 and psr4 especially but for conflict logic in general. :-)

**Comment by GrahamCampbell** [comment]
> Will it work?

Yeh, it should work, since we check for conflicts right at the end.

**Comment by Soullivaneuh** [comment]
Ok so for my case, I just have to check conflict on merged preset and manually enabled fixers. Am I right?
