### ISSUE TITLE
Use StyleCI/Config instead of importing the file

### ISSUE THREAD

**Issue by Soullivaneuh** [Soullivaneuh/php-cs-fixer-styleci-bridge#14]
Include [styleci/config](https://packagist.org/packages/styleci/config) and use the Config class directly.

This could be done once PHP minimum version support will be 5.6 or higher.

**Comment by GrahamCampbell** [comment]
Or 5.4 if I lower the min version in the config repo and revert the array constant stuff.

**Comment by GrahamCampbell** [comment]
I don't really want to go lower than 5.4, and ideally not lower than 5.5.9.

**Comment by Soullivaneuh** [comment]
I'll keep same PHP version support than PHP-CS-Fixer for now.

**Comment by Soullivaneuh** [comment]
But I'll prepare a PR for it. It will be merged later. :+1:

**Comment by Soullivaneuh** [comment]
@GrahamCampbell Can you consider to make styleci/config?

The PR I'm preparing could be merged faster if php requirement is lower.

In any case, this PR will be merged only when php-cs-fixer php version support will match your package.

**Comment by Soullivaneuh** [comment]
`StyleCI/Config` does not exist anymore.

See https://github.com/Soullivaneuh/styleci-fixers/issues/1.
