### ISSUE TITLE
Run PHPCSFixer

### ISSUE THREAD

**Issue by theofidry** [Soullivaneuh/php-cs-fixer-styleci-bridge#40]
How do you run the PHPCSFixer with the specified config? For some reason it skips all the files for me if I pass the `.php-cs` file as a config file :(

**Comment by Soullivaneuh** [comment]
> if I pass the `.php-cs` file as a config file :(

What do you mean by "pass the config file"? BTW, it's `.php_cs`, not `.php-cs`.

Could you please provide your `.php_cs` and your `.styleci.yml` files and the complete entered command for fixer?

**Comment by Soullivaneuh** [comment]
ping @theofidry.

Did you solve your problem?

**Comment by theofidry** [comment]
Err actually can't remember, I'll open it again if I run into the issue again.
