### ISSUE TITLE
Clean Fixers / Presets before set

### ISSUE THREAD

**Issue by Soullivaneuh** [Soullivaneuh/php-cs-fixer-styleci-bridge#42]
Since 2.0, double fixers wont be accepted: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1442

On the bridge, after fixers resolving, clean the list to avoid duplicate.

Take care of #41 too.

**Comment by GrahamCampbell** [comment]
StyleCI should already do this anyway?

**Comment by GrahamCampbell** [comment]
Since we already have that restriction in our code.

**Comment by Soullivaneuh** [comment]
In our code maybe, I don't think so for mine. :-)

**Comment by Soullivaneuh** [comment]
Same fixers exception is only for fixer registration, not configuration. Closing.
