### ISSUE TITLE
Get an updated-config

### ISSUE THREAD

**Issue by lucasmichot** [Soullivaneuh/php-cs-fixer-styleci-bridge#57]
Any possibility to get an up-to-date config ?
cc/ @GrahamCampbell

**Comment by lucasmichot** [comment]
Or maybe https://github.com/StyleCI/SDK

**Comment by GrahamCampbell** [comment]
@lucasmichot Duplicate of https://github.com/Soullivaneuh/styleci-fixers/issues/1. ;)

**Comment by Soullivaneuh** [comment]
Hi @lucasmichot,

WIP on https://github.com/Soullivaneuh/styleci-fixers/pull/2.

Will update the bridge right after that! :wink:

**Comment by Soullivaneuh** [comment]
Here you go: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/releases/tag/v1.6.0
