### ISSUE TITLE
Preset stuff is wrong

### ISSUE THREAD

**Issue by GrahamCampbell** [Soullivaneuh/php-cs-fixer-styleci-bridge#8]
StyleCI's presets are NOT the same as php-cs-fixer levels I'm afraid.

**Comment by Soullivaneuh** [comment]
Could you elaborate?

I especially avoid the `recommended` preset, but what about the `symfony` one? Could I have the diff?

And maybe, could we have a more convenient solution like a preset that respect php-cs-fixer and another one with a custom name?

**Comment by Soullivaneuh** [comment]
@GrahamCampbell At least, I can maybe work to get fixers and preset from your own repositories instead of CS fixer but we have to get this working for PHP 5.3+. Could this be possible?

Related: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/issues/6#issuecomment-142296204

**Comment by Soullivaneuh** [comment]
Partially fixed on #9.
